### ISSUE TITLE
Documentation doesn't actually mention how to use it.

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#116]
I've read the documentation twice and there's no example on _how to actually use the module_. Something like:

```
>>> import keyring
>>> keyring.set_password("test", "username", "password")
>>> keyring.get_password("test", "username")
u'password'
```

Would do the trick.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/116
- Originally reported by: Stavros Korokithakis
- Originally created at: 2013-09-27T13:52:58.710

**Comment by jaraco** [comment]
Add some basic usage to the docs. Good suggestion by Stavros. Fixes #116.

→ <<cset f142444c8945>>

---

Original comment by: Jason R. Coombs

**Comment by dd-ssc** [comment]
10 years later, almost to the day, and this issue still applies.

From [Using Keyring](https://github.com/jaraco/keyring?tab=readme-ov-file#using-keyring):

```
 ...
>>> keyring.set_password("system", "username", "password")
 ...
$ keyring set system username
 ...
```

What is `system` ? 🤷🏻‍♂️

How do I use `keyring` in the most basic real-world scenario ? 🤷🏻‍♂️🤷🏻‍♂️
How do I get / set secrets from / in any of the four recommended keyring backends supported
(macOS Keychain, Freedesktop Secret Service, KDE Wallet, Windows Credential Locker) ? 🤷🏻‍♂️🤷🏻‍♂️🤷🏻‍♂️

I do remember having looked into `keyring` quite a few times in the last couple of years, but gave up on it quickly each time because I simply didn't understand how to use it. Now I'm somewhat forced to make it work for me because it is the only somewhat reasonable means of authentication for [`uv`](https://github.com/astral-sh/uv) - at least until they've added support for a Rust-based solution.

I'd be happy to contribute documentation, but I can't because I don't know how `keyring` is supposed to work 😞

**Comment by jaraco** [comment]
Well, this issue was addressed to some extent. Probably a new issue should be opened if the solution is inadequate. I'll move your questions to a new issue.
