### ISSUE TITLE
Blank passwords

### ISSUE THREAD

**Issue by zerkms** [jaraco/keyring#159]
I understand it was changed in 2009, but is there any chance there is a workaround to have an empty password for the wallet?

I'm using `keyring` indirectly through `mercurial_keyring` and it's a bit inconvenient.

Thanks.

**Comment by jaraco** [comment]
Seems an odd use-case to support blank passwords. I just tested the latest version and it works for me with the WinVaultKeyring.

```
>>> import keyring
>>> keyring.set_password('foo', 'bar', '')
>>> keyring.get_password('foo', 'bar')
''
```

That doesn't mean it works for all keyrings. If you or someone is willing to expand the tests to include a blank password, and then also fix any failing tests in the supported keyrings, it doesn't seem like an unreasonable request.

**Comment by zerkms** [comment]
I asked about the blank master password which is currently denied by this: https://github.com/jaraco/keyring/blob/51119eb80e92a178400ab90e99096877882fcb41/keyring/backends/file.py#L182

**Comment by jaraco** [comment]
Aha. So the issue is with the encrypted file keyring. The reason that a non-blank password is required is because encryption has no value if there's no secret information. That is, if you had a blank password, any adversary could trivially decrypt the keyring.

If you don't want to have any security on your keyring, I suggest instead configuring you environment to use the plain text keyring, which won't prompt for a password at all.
