### ISSUE TITLE
hgtools in setup_requires breaks installs without internet access

### ISSUE THREAD

**Issue by mroark1m** [jaraco/keyring#169]
Was trying to create a repeatable network-free install and ran into this, very similar to this issue:

https://github.com/pypa/pip/issues/410

Even though I've downloaded keyring-5.3.zip and created a local index, I can't install it with pip, it tries to download hgtools and times out. Even if I add hgtools to the local index it still tries to go to pypi. Actually even if hgtools is already installed it still goes to pypi.

**Comment by jaraco** [comment]
> Actually even if hgtools is already installed it still goes to pypi.

I'm unable to replicate this behavior. For example:

```
$ sudo sh -c "cat >> /etc/hosts"
127.0.0.1 pypi.python.org
$ python -m venv env
$ # demonstrate that PyPI is unreachable
$ env/bin/pip install requests
Collecting requests
...
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))': /simple/requests/
  Could not find any downloads that satisfy the requirement requests
  No distributions at all found for requests
$ env/bin/pip install dist/hgtools-6.3.zip
Processing ./dist/hgtools-6.3.zip
Installing collected packages: hgtools
  Running setup.py install for hgtools
Successfully installed hgtools-6.3
$ env/bin/pip install dist/keyring-5.3.tar.gz 
Processing ./dist/keyring-5.3.tar.gz
Installing collected packages: keyring
  Running setup.py install for keyring
    Installing keyring script to .../env/bin
Successfully installed keyring-5.3
```

As maintainer of hgtools and now co-maintainer of setuptools_scm and also as maintainer of setuptools, I'm very familiar with this issue. In my company, we use hgtools and now setuptools_scm extensively, and we maintain a private repository internally.

Unfortunately, due to [distribute 338](https://bitbucket.org/tarek/distribute/issues/338/unable-to-specify-custom-index-for) and pip 410, as you referenced, `setup_requires` dependencies can be somewhat tricky to resolve in isolated environments. The issue is inherently tricky - the `setup_requires` hook happens very early in the invocation of `setup.py` in order to enable the required distribution to customize the execution.

That said, you have a few options. The first is to install hgtools (or later setuptools_scm). I don't recommend this approach because it is brittle - you have to keep up-to-date the hgtools package that's compatible with all libraries you might be installing... and if two packages depend on mutually exclusive versions of hgtools, you're stuck.

The second option is within your python environments, configure easy_install to only ever install from the private index. Something like this bash script will work:

```
DISTUTILS_CFG=`python -c "import distutils, os; print(os.path.dirname(distutils.__file__))"`/distutils.cfg
cat >> $DISTUTILS_CFG << EOF
[easy_install]
allow_hosts=index.example.com
index_url=https://index.example.com
EOF
```

Those distutils directives to easy_install signal to easy_install (used by setup_requires) to only allow packages to be downloaded from hosts named 'index.example.com' and to use the index at https://index.example.com to download packages. Generally, the latter is only required, but including the former also prevents packages themselves from using find_links or similar to cause network attempts.

A third option would be to pursue a fix for the aforementioned distribute issue and/or the proposed solution in pypa/pip#2910.

Since you bring it up, I'll make the switch to setuptools_scm right away to help you avoid addressing the issue twice.

Hope that helps and good luck!

**Comment by jaraco** [comment]
I just thought of another possibility - you could build a wheel of keyring (or keyring could even publish wheels), which when installed with pip would bypass the setup_requires step.

**Comment by jaraco** [comment]
For the 5.4 release, I uploaded a wheel. Please give that a try in your private index and see if that helps address the issue.

**Comment by mroark1m** [comment]
Thanks for the wheel, I'll try that and also see if I can reproduce my issue with hgtools (just out of curiosity, I think wheel should solve it).

**Comment by mroark1m** [comment]
I got it. hgtools was getting installed in the same pip install invocation. Once I separated it out into a separate and prior pip install it worked. Thanks!

**Comment by mitya57** [comment]
@jaraco Can you please commit the latest release (5.4) to Git please?

I have tested the tarball, and it seems to work fine even when I don't have `setuptools_scm` installed. So thanks for fixing this issue (and also thanks for finally switching to `.tar.gz` tarballs)!
