### ISSUE TITLE
No Recommended backend was available on all systems I test my application on

### ISSUE THREAD

**Issue by mohamey** [jaraco/keyring#204]
I've been writing a desktop application in python that requires users to log in and I've rather enthusiastically adopted the use of Python Keyring to save users passwords. The module worked fine on the Windows 10 PC I wrote the application on, but when I try to use the set_password command on anything other than the original system I get the response "No Recommended backend was available". I havent had much luck setting the backend manually either using the set_keyring command (for windows "keyring.set_keyring(keyring.backends.Windows.WinVaultKeyring)" would return "The Keyring must be a subclass of KeyringBackend. When using the python interpreter, calling keyring.get_keyring() returns "keyring.backends.fail.Keyring object at 0x7f94441aee50". I've posted more details of my problem and the code on [stack overflow](http://stackoverflow.com/questions/35073722/trying-to-use-the-python-keyring-module-to-save-passwords-to-the-system-for-my-a). I'm not sure if this is a problem through my own usage of the module, but it seems to occur on every system I try to run my application on.

**Comment by jaraco** [comment]
For the `set_keyring` command, you probably need to pass an instance of a keyring. The error message could be more precise.

The problem is that "on all other systems" probably means Linux. If on OS X, you also would have gotten a suitable backend automatically.

Linux users have it less obvious, although the latest README describes a [section on configuring for headless Linux systems](https://github.com/jaraco/keyring/blob/master/README.rst#using-keyring-on-headless-linux-systems).

Another easy solution is to, in addition to installing keyring, also install `keyrings.alt`, which includes the insecure keyrings and will always provide some usable backend, even if it stores the user's passwords in plain text on disk.

Hope that helps.
