### ISSUE TITLE
PyPI keyring 8.4 packaged incorrectly

### ISSUE THREAD

**Issue by enkore** [jaraco/keyring#210]
On PyPI there are two downloads for 8.4: The source / .tar.gz and a Python wheel:

https://pypi.python.org/packages/source/k/keyring/keyring-8.4.tar.gz#md5=c4c29fcd1d63bf9e299c524ba4fdc04a
https://pypi.python.org/packages/3.5/k/keyring/keyring-8.4-py2.py3-none-any.whl#md5=014f3c41c38f31ad035be909bf370ee4

While the source only contains what is in this repository, the wheel contains additional backends that were moved to `keyrings.alt`

**Comment by jaraco** [comment]
Thanks for the report.

This issue bites me almost every time I delete a file from a package. I'm all but certain the issue is due to the deleted files lingering in my `build` directory. I've purged them using `hg purge --all` (I use hg as my git client), and re-released keyring as 8.4.1. Please let me know if that doesn't correct the issue.

For the record, I would expect these files to have a minimal impact on behavior as `keyring.backend._load_backends` no longer contains a reference to those modules.

**Comment by enkore** [comment]
Thanks!
