### ISSUE TITLE
Need to set folder and appid for kwallet backend

### ISSUE THREAD

**Issue by barry-scott** [jaraco/keyring#213]
It is desirable to allow the backend to be configured with items like the folder and appid used
for the kwallet backend.

I have not looked at the other keyrings yet, but suspect they have their own OS specific config that it would be nice to set.

I think the change is to stop creating the backend on "import keyring" but to do it on demand when one of the get_xxx is called. Then an init_keyring() call can be made before any get_xxx calls that sets the backend config before its created.

**Comment by jaraco** [comment]
Is it not possible to simply call `keyring.core.set_keyring(custom)` on the customized keyring with folder and appid set? Or call `keyring.core.init_backend()` after customizing the behavior?

I acknowledge that it's somewhat annoying to have the behavior invoked as part of the import, but that's the current expectation, and may introduce violated expectations if changed, so I'd rather not make the change unless it's well-justified. What's the advantage of creating the backend on demand during calls to `get_*`?

**Comment by barry-scott** [comment]
Using set_keyring(custom) is not convenient because of the the way you implement the backends.
You force the self.folder and self.appid in the connected method.
You would need to implement a **init** on the backends that took the config and stop setting  it in connected(). For example:
class KWallet:
    def__init__( self, folder='Python', appid='Python app' ):
       self.folder = folder
       self.appid = appid

The on demand is just because of the way you structure the library.
Doing important work as a side effect of "import keyring" means you have to undo that and then create the backend that is appropriate with the config data it needs.

The Windows backend also needs to have configuration data to set the "TargetName" value following MSDN guidelines. Google for CredWrite to get the MSDN for the API then click thru to the CREDENTIAL struct for the docs on use of the values.

I havn't read enough of the OS X docs on Keychains to understand the important config that it needs.

It may well be the case that fixes the API as I need is not possible ginve the current state of keyring.
One possibility is to create a keyring2 module that fixes the issues.

**Comment by jaraco** [comment]
I agree the kwallet implementation is a little funky; setting static attributes in the `connected` method is awkward, and maybe could be improved. What's worse is that the 'service' name is being embedded in the "key", whatever that's supposed to be.

Still, that issue is separate from the original critique, which was suggesting that the backend selection on import is somehow preventing the creation of a different backend. I don't think it is, but if you want to file a separate ticket on that mechanism, you may.

> You would need to implement a init on the backends that took the config and stop setting it in connected().

You could do that now with a bit of a hack:

```
class TweakedKWallet(kwallet.DBusKeyring):
    @property
    def folder(self):
        return vars(self).get('folder', 'Python')

    @folder.setter
    def folder(self, val):
        "ignore the value"

    @property
    def appid(self):
        return vars(self).get('appid', 'Python program')

    @appid.setter
    def appid(self, val):
        "ignore the value"

backend = TweakedKWallet()
vars(backend).update(folder='custom folder', appid='custom appid')
keyring.core.set_keyring(backend)
```

I acknowledge that is ugly and hacky, but I suspect it would enable what you seek.

Perhaps it does make sense to allow the folder and appid to be customized, but since the main API of keyring is meant to be the get/set/delete password functions, and those are meant to be invoked without additional parameters, I struggle a bit to see how a suitable values would be solicited.

> The Windows backend also needs to have configuration data to set the "TargetName" value following MSDN guidelines. Google for CredWrite to get the MSDN for the API then click thru to the CREDENTIAL struct for the docs on use of the values.

I'm familiar with the API. Have you read the code? The TargetName is set to the 'service' value.

> It may well be the case that fixes the API as I need is not possible

Perhaps you could start by describing the use case you have and how you expect keyring could be adapted to fit that use case?

**Comment by jaraco** [comment]
With this latest commit, the override is much less hacky, but will only work with future releases:

```
backend = TweakedKWallet()
backend.folder = 'custom folder'
backend.appid = 'custom appid'
keyring.core.set_keyring(backend)
```
