### ISSUE TITLE
Password Prompt when kwallet or gnome-keyring not installed

### ISSUE THREAD

**Issue by kyledouglas** [jaraco/keyring#225]
python-keyring defaults to storing creds in crypted_pass.cfg if no gnome or kwallet manager is available from what I understand. When trying keyring.get_password() I am prompted for a password. Is there a way to store this value and pass on prompt? typical input methods are not working. 

Upon executing script 
`Please enter password for encrypted keyring:`

http://docs.halon.se/halonctl/modules/keyring.html - unrelated statement I am trying to confirm
`On Linux, if you do not have either GNOME Keyring, kwallet or another Secret Service-compatible facility available, it will fall back to storing credentials in an encrypted file. This is not quite as secure, but still better than plaintext.`

Keyring location
`[dm-brs-lm01: SU: event-schedule/event-schedule 1051] python -c "import keyring......
//.local/share/python_keyring`

**Comment by jaraco** [comment]
Keyring no longer defaults to the encrypted file keyring unless you have [keyrings.alt](https://pypi.io/project/keyrings.alt) installed.

> Is there a way to store this value and pass on prompt? typical input methods are not working. 

No. That's the nature of an encrypted file - the secret to unlock it must be stored somewhere. That's why that backend isn't really recommended... because it requires user input. You instead want to use one of the recommended backends which take advantage of the system keyrings and user authentication to unlock those keyrings.

If you really don't want to use the recommended keyring, but you don't want to have to enter a password each time, you could configure the Plaintext keyring, which will store the passwords in a file, but not encrypt them (which is only nominally less secure than storing them encrypted with the encryption password alongside them).

I hope that helps.

**Comment by kyledouglas** [comment]
That helps. I guess I was trying to avoid the inevitable. Looks like Ill be using one of the recommended back ends.
