### ISSUE TITLE
OS X El Capitan: if password is not found, raise an exception rather than returning empty string

### ISSUE THREAD

**Issue by jbarlow83** [jaraco/keyring#261]
As in the title, keyring returns an empty string for all passwords that do not exist in the keychain rather than raising an exception for failures.
```
import keyring
keyring.get_password('doesnotexist','doesnotexist') --> returns ''
```

**Comment by jaraco** [comment]
It's by design that get_password returns None (not empty string) when no password exists:

```
$ python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.get_password('doesnotexist', 'doesnotexist')
```

Changing that behavior would break a lot of use cases such as:

```
pw = keyring.get_password(...) or getpass.getpass()
```

Interestingly, I don't see any tests that assert that behavior. I do see that the readme explicitly states "If the password does not exist, it will return None."

I'll write a test that asserts this behavior.

**Comment by jaraco** [comment]
Oh, [I see it now](https://github.com/jaraco/keyring/blob/master/keyring/tests/test_backend.py#L55-L56).
