### ISSUE TITLE
Supporting time limited keys (eg remember for an hour)

### ISSUE THREAD

**Issue by rogerbinns** [jaraco/keyring#262]
Is it possible to have keys only remembered for a certain amount of time, such as "remember this key for the next hour"?  The functionality doesn't appear to be exposed or documented.  

I'm only concerned about Linux where you can be prompted for passwords in the desktop and have a choice of forget immediately, remember for an hour or remember forever.  I'd like to mimic the remember for an hour behaviour.

**Comment by frispete** [comment]
keyring is the wrong project for what you're looking for.

Check out [Fernet](https://github.com/fernet/spec/blob/master/Spec.md).
A python implementation is available [here](https://github.com/pyca/cryptography/blob/master/src/cryptography/fernet.py). You should combine this with a KDF, nowadays preferably with argon2..

**Comment by rogerbinns** [comment]
@frispete  Thanks for the pointer, but that seems like a significant amount of additional work.  And I'm not sure it actually solves the problem.

I am expecting that since the desktop environments already have options for how long "passwords" are remembered, that keyring can expose similar functionality.

**Comment by jaraco** [comment]
The password that unlocks the keyring is only used in keyrings.alt in the encrypted file keyring, which is considered deprecated because of its security implications.

Keyrings.alt could do what you propose, but it would require storing the encryption password somewhere in plaintext on the disk (how else could it be achieved?).

My recommendation is that you rely on the recommended keyrings in keyring, which rely on system credential vaults and their integrated security implementations. If you really feel like this feature is something that keyrings should support, I recommend implementing it as a third-party library and demonstrating the technique. At that point, perhaps we can consider adopting it in the library, especially if it solves these issues above.

**Comment by rogerbinns** [comment]
@jaraco it isn't the keyring password that I am concerned about, but instead something stored in the keyring.

As an example, say I process pdf files on the command line.  Sometimes they have passwords.  When I encounter one, I ask the user for the pdf password, and use keyring to remember it.  However I don't want keyring to remember that password forever, only an hour or so.  I can't make the script go and clear out the password an hour later since it won't be running. 

I can't tell how the desktop environments implement the choice of remembering passwords for no time, for a set period of time, for the session or indefinitely.  But they use keyrings and hence the functionality exists, and I was hoping that python-keyring could expose it.

**Comment by jaraco** [comment]
@rogerbinns Oh, I see. Password expiration is an interesting case, but I think still falls prey to some of the same challenges. For example, is it okay for keyring to leave the password saved/stored even after it has expired? keyring runs in-process, so doesn't have any mechanism to deal with events, such as password expiration, though it could theoretically clear expired passwords on a subsequent run.

Can you provide more detail to describe how a library like keyring might implement such a feature? What would the API look like? How would the desired behavior be achieved? How would it work across different backend implementations?

**Comment by rogerbinns** [comment]
@jaraco you are right in that there isn't much point implementing it in-process, although an atexit handler that does garbage collection would at least ensure expired ones could be removed some of the time.  Possibly also do the same on opening a keyring.

I'm considering the Linux desktop environment where keyring (I assume) is using Secret Service over dbus.  Whatever is implementing Secret Service can then do the garbage collection, as well as respecting time to live.  I believe that is something like Gnome Keyring.  

In terms of API, all I'd want is a time to live parameter on the keyring.set_password method.  If the backend has proper time to live support then use that.  If not then something like my first paragraph (library manually  garbage collecting/expiring).

**Comment by rogerbinns** [comment]
@jaraco I've figured out how to implement this on Linux, and it is very Linux specific.  Perhaps adding this as another backend, or just deciding it is out of scope for the keyring project?

The solution is to use [keyctl](http://man7.org/linux/man-pages/man1/keyctl.1.html).  The keyrings are implemented by the kernel and non-persistent across reboots.  They can be accessed within the same process tree, by the same user, across a session and various other scopes.

This will add a key to the user-session (@us) scoped keyring and set a 1 hour (3,600 seconds) timeout:

````
$ echo -n 'the secret' | keyctl padd user KEYNAME @us
... prints a keyid like 977746739 ....
$ keyctl timeout 977746739 3600
````

This is how you search for a key:
````
$ keyctl search @us user KEYNAME
... prints a keyid like 977746739 or return code non-zero and this
keyctl_search: Key has expired
````

This is how you get the contents of a key on stdout:
````
$ keyctl pipe 977746739
````

**Comment by jaraco** [comment]
> In terms of API, all I'd want is a time to live parameter on the keyring.set_password method. If the backend has proper time to live support then use that. If not then something like my first paragraph (library manually garbage collecting/expiring).

When I try to think about how the docs would describe this API, it seems awkward. Lots of conditionals, references to specific backends, etc. I think this approach goes against the simplicity of keyring. Perhaps better would be for the `set_password` to accept a `time_to_live` or `ttl` parameter, but if the backend doesn't support robustly expiring the password, it will raise an error rather than store it. At least that way, if one passes a TTL, they can expect it to be honored and or at least never leave a password longer than TTL. Then one could implement a backend for `keyctl` that would implement this interface.

Even better might be a generic interface that passes any keyword arguments to `get_password` or `delete_password` or `set_password` to the backend. Backends that don't accept any keyword passed will fail as the signature isn't met. In this way, keyring wouldn't have to be in the business of endorsing specialized behavior in some backends.

Even without this feature in place, you could still implement a backend for keyctl and customize its behavior with only one additional call:

```
import keyring
import datetime
keyring.core.get_keyring().TTL = datetime.timedelta(hours=1)
keyring.set_password(...)
```

In this description, the TTL would be ignored on most backends but on an backend that honored the TTL attribute on the backend, it would have its effect. If you wanted it to fail more loudly, you could instead make the interface `.set_ttl()`... which would fail unless the setter was present.

How do these ideas strike you?

**Comment by rogerbinns** [comment]
I did notice that the Secret Service (dbus?) api doesn't just store a "username" and credential, but rather that you can also supply a dict of arbitrary key/values that also get stored and retrieved.  I don't know how common that is with other backends.  If other backends are more information rich then it would probably be a good idea to enhance the current apis in a similar manner like you suggest.

However keyring is really simple right now, and virtually impossible to screw up using it as a developer that reads the least amount of docs (ie almost all developers).  Broadening the API would allow room for unexpected or unintended behaviour.

Perhaps an evolutionary approach is to expose all functionality in each backend, and have a way of talking to the backend directly for those developers who know what they are doing.  Then a year later look at how many are taking advantage of that.  If none are then no more work is needed.  If many are, then making common uses available via the generic api seems like a good idea.

In your shoes right now, I'd close this issue and wait till there is more demand for additional functionality.

**Comment by fschulze** [comment]
On OS X this is handled by the system. I can tell it to lock my keyring when the screen safer starts. After that when python-keyring asks for the password, I have to unlock the keyring again. I'd imagine that this is the right way this should work, since the preference would be global for the user. Or am I misunderstanding what you want to achieve?

**Comment by rogerbinns** [comment]
@fschulze you are describing something different - how often you have to unlock a keyring.

This is about keys in the keyring.  I want the keys to go away if not used for a time period (eg an hour).  This is to ensure the keyring doesn't fill up with temporary keys, but the ones that are (re)used do remain around.  

For example imagine implementing something like a PDF or zip file viewer.  Some of them are password protected so you ask for and remember the password.  But you don't want to remember every password forever. [This](http://3.bp.blogspot.com/-0ouvJrCSWI8/VGcGO-njygI/AAAAAAAAATY/W4wqvnnF5vc/s1600/require++password(www.linux-all-over.blogspot.com).pngl) is what the linux desktop does now - imagine adding an option to remember for an hour after last use.

**Comment by jaraco** [comment]
> Perhaps an evolutionary approach is to expose all functionality in each backend

As I consider this proposition, I realize two things. To the extent that the keyring exposes the underlying behavior, that functionality is exposed, sometimes through other packages like secretservice, and other times through the API layer embedded in keyring. To the extent that behavior has a common API, that's the primary API of keyring (get/set/delete). There's no intermediate, low-level API that's common to the backends.

So I don't think there's anything to be done with this proposition.

What I recommend for now is that you create a Keyring subclass and use that to prove the usage and solve the needs for your use-case, at which point you'll have a concrete implementation that you can share with this project and that others can adopt if they choose. And if it shows promise of having general applicability, we can then consider adopting it in the keyring library itself.

Best of luck.
