### ISSUE TITLE
What licence applies for this project, please?

### ISSUE THREAD

**Issue by devcurmudgeon** [jaraco/keyring#263]
I ask because the project was mentioned at Open Source Leadership Summit as an example without detectable licence information. I see readme mentions MIT, but there doesn't appear to be a licence file

**Comment by jaraco** [comment]
https://github.com/jaraco/keyring/blob/master/setup.py#L43

It is detectable, as [warehouse detects it](https://pypi.org/project/keyring/).

For more information, see [skeleton 1](/jaraco/skeleton/issues/1).

**Comment by devcurmudgeon** [comment]
While I appreciate why you've done it this way, would you consider including SPDX metadata instead (or as well)?

**Comment by mitya57** [comment]
In my opinion, just saying that the license is MIT is very imprecise.

Wikipedia says in http://en.wikipedia.org/wiki/MIT_License#Various_versions:

> Because MIT has used many licenses for software, the Free Software Foundation considers "MIT License" ambiguous. "MIT License" may refer to the "Expat License" (used for Expat) or to the "X11 License" (also called "MIT/X Consortium License"; used for the X Window System by the MIT X Consortium).

I would prefer if you actually included a license file (GitHub [recommends it too](https://help.github.com/articles/licensing-a-repository/)), but at least please specify the variant of MIT license you want to be using (i.e. Expat).

**Comment by jaraco** [comment]
> include SPDX

I looked into this proposal and it seems it's [not well defined](https://github.com/pypa/interoperability-peps/issues/46) what it means to include SPDX metadata.

> instead (or as well)?

https://xkcd.com/927/

*sigh*. The main reason I wanted not to maintain the metadata and a separate license file was to reduce the number of places the license is indicated to limit the possibility of confusion or inconsistency. Adding another just makes matters worse. Once there's a consensus solution that allows declaring the license clearly and unambiguously and have that metadata mechanically cascade through the various presentations (source code, package metadata, runtime, etc), I am reluctant to just add files or entries to serve specific use cases.

See also #138.

**Comment by devcurmudgeon** [comment]
@jaraco i understand, and agree - license declaration is a mess so far.

I know that the SPDX project is *aiming* to be the de-facto approach for defining license clearly and unambiguously, but the docs don't exactly make it obvious what to implement at this point. I'm studying it more closely for another project, will report back here if I can come up with a convincing justification and/or patches :)

**Comment by pombredanne** [comment]
@devcurmudgeon  FWIW, the license choices available for use in Python packages metadata are listed here: https://pypi.python.org/pypi?:action=list_classifiers and correctness is enforced when uploading to Pypi. This package declares itself as using both the MIT and the Python licenses.

@jaraco you wrote:
> The main reason I wanted not to maintain the metadata and a separate license file was to reduce the number of places the license is indicated to limit the possibility of confusion or inconsistency. 

The metadata approach is fine.  Now I have two remarks:
1. your downstream users are automatically not compliant with the licenses because the code you redistribute does not contain the license texts proper which is an essential condition of the MIT and Python licenses themselves. (See https://enterprise.dejacode.com/license_library/Demo/python/#license-conditions ) 
2. as a side note --as you may know-- wheels have very limited provisions to include extra license texts (e.g. a single text file in the METADATA using a setup.cfg entry) and do not honor MANIFEST.in entries ... See https://bitbucket.org/pypa/wheel/issues/138/include-more-than-one-license-file-or ... This eventually makes a wheel subject to the same issue as described in 1. even if you were to include the MIT and Python license texts in an sdist

3. on SPDX license ids in general and Pypi Trove classifiers: the trove classifiers are not perfect as they are, but updating them is done elsewhere and not here. That said, using them instead of or in addition to the current classifiers would likely be a major step forward. SPDX ids have been adopted by NPMs and Ruby FWIW. 

I guess I/we should start working on a PEP towards this.
@devcurmudgeon Are you interested by this? We could ask @jaraco to possibly sponsor us for this PEP? 
This is not a huge amount of work, but this will likely prove to be controversial and subject to lengthy discussions. 

@devcurmudgeon @jaraco Finally the latest https://github.com/nexB/scancode-toolkit/ develop detects these alright (I just pushed a few extra detection rules to make sure this was the case). 

@devcurmudgeon the correct license is not just MIT but MIT and Python.

**Comment by jaraco** [comment]
I'm not sure what's entailed in being a PEP sponsor, but I would be willing to provide some sort of endorsement of the process.

**Comment by devcurmudgeon** [comment]
@pombredanne i'm interested, yes - similar to @jaraco i  have no idea what's involved though

**Comment by pombredanne** [comment]
@jaraco  Thanks! This should be light and only if you really feel like it after we came up with a draft
@devcurmudgeon I invited you and Jason to a new repo to start a draft. The process is explained there: https://www.python.org/dev/peps/pep-0001/

**Comment by pombredanne** [comment]
@devcurmudgeon I started a basic draft/skeletton at https://github.com/pombredanne/spdx-pypi-pep/blob/master/pep-xxxx.txt and we can take it from there.

**Comment by devcurmudgeon** [comment]
@jaraco SPDX project has now improved its documentation for maintainers at https://spdx.org/using-spdx#identifiers

This now seems unambiguous and easy to apply to the code - would you consider adopting this, or accepting patches?

**Comment by jaraco** [comment]
@devcurmudgeon That spec seems to be suggesting an extension to the "put the license in every file" technique, which adds to the duplicity and potential for deviation. What happens if one declares one license in the SPDX but uses the text of another (or tweaks the text)? What does it mean of some files have different licenses than others? What does it mean if a file is contributed to the project without a license or with a conflicting license? From my brief skim, it doesn't solve the problem of referencing a license in metadata at the project level and applying that license to files in the project.

What I'd really like is a way to _declare_ a license without having to spell it out in each project (or worse in each file). The declaration should cascade, such that a single reference at the project level will apply to all files in the project, but still allow projects to override or extend the license at the project or file or component level, much in the way cascading style sheets work for HTML. It should appear declared in the source and that declaration should be incorporated into the package build, such that a developer could simply in one place declare the license for the project and let the tooling handle the rest.

**Comment by jaraco** [comment]
> would you consider adopting this, or accepting patches?

Honestly, I'm growing weary of the constant pressure to more plainly incorporate license text into the projects, so I'm going to just let others manage it. I've been thinking of moving the projects I maintain to [jazzband](/jazzband). If I did that, then you could add licenses wherever you want and cut new releases. The main reason I haven't done that yet is because I don't yet have documentation enough to guide people on how to cut releases (tl;dr use annotated tags). I'd probably want to do that in [the skeleton](/jaraco/skeleton).

I'll grant you both access to the repo; do whatever you think is best.
