### ISSUE TITLE
The documentation should be clear of whether password can be bytes or only unicode

### ISSUE THREAD

**Issue by mitya57** [jaraco/keyring#275]
All the below applies to Python 3 only.
Some backends (i.e. SecretStorage) accept bytestrings as passwords, others (the file backend) do not.

But there is some code that tries to use bytestrings as passwords and [fails](https://bugs.launchpad.net/ubuntu/+source/python-keyring/+bug/1685547) with the file backend.

We should either fix the file backend (which is now in `keyrings.alt`) and make sure all other backends support bytes too, or fix the documentation to clearly say that the password should be a unicode string.

**Comment by jaraco** [comment]
Agreed. The interface should be well defined.

My instinct is to only support unicode strings for inputs. Although this would possibly break existing use cases, such cases could always take raw byte strings and represent them in Unicode, either by decoding as ascii or latin-1 or as an appropriate codec for the content.

So if someone wants to store a raw byte key for an encryption algorithm, they can do it thus:

```
key = b'...' # some byte string
password = key.decode('latin-1')
keyring.set_password(system, username, password)
...
revived_pw = keyring.get_password(system, username)
key = revived_pw.encode('latin-1')
```

Since latin-1 provides a mapping for all bytes 0x00-0xFF, that technique should work in all cases. If there's a compelling use case for the need to store bytes, I recommend keyring to provide an additional interface to set and get bytes, perhaps `get_password_bytes` and `set_password_bytes`.

**Comment by mitya57** [comment]
OK, then we should update the documentation.

Maybe also `keyring.core.set_password` can raise a meaningful TypeError when the password is not unicode?

**Comment by jaraco** [comment]
> Maybe also ``keyring.core.set_password`` can raise a meaningful TypeError?

Unfortunately, the current API doesn't require that backends call any common behavior where such a check could be implemented. Each backend would have to implement this check itself. For that reason, I'm disinclined to invest the effort to perform the checks. But I'm not opposed if someone else wants to expend the effort.
