### ISSUE TITLE
secretstorage.exceptions.SecretServiceNotAvailableException: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

### ISSUE THREAD

**Issue by AdilHindistan** [jaraco/keyring#280]
I saw the comment on issue #258. 
```python
>>> import keyring.backends.SecretService as ss
>>> ss.Keyring.priority
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "keyring/backends/SecretService.py", line 34, in priority
    "Unable to initialize SecretService: %s" % e)
RuntimeError: Unable to initialize SecretService: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
>>> secretstorage.dbus_init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "secretstorage/__init__.py", line 52, in dbus_init
    e.get_dbus_message())
secretstorage.exceptions.SecretServiceNotAvailableException: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

Running this on a linux server, accessed via ssh.  export DISPLAY=":0" produced another error:
```
RuntimeError: Unable to initialize SecretService: /bin/dbus-launch terminated abnormally without any error message
```

Any ideas?

**Comment by mitya57** [comment]
Please follow the instructions at https://github.com/jaraco/keyring/blob/master/README.rst#using-keyring-on-headless-linux-systems if you want to get Secret Service running on a headless system.

**Comment by frispete** [comment]
..and/or check out https://github.com/frispete/keyrings.cryptfile, if you're looking for decent file based keyring operations...

**Comment by chdecultot** [comment]
Hi,

I am having the exact same issue when using Google oauth2client:

```
from oauth2client.contrib.keyring_storage import Storage
store = Storage('GCal', user)
credentials = store.get()
```

How can I use keyring on headless linux directly from an application ? 
My apologies, I'm not familiar at all with keyring and just want to use oauth2client possibilities.

**Comment by mitya57** [comment]
@chdecultot Sorry for not replying earlier, found this when cleaning up my mailbox.

> How can I use keyring on headless linux directly from an application?

You can install [keyrings.alt](https://github.com/jaraco/keyrings.alt) and use one of the [file-based keyrings](https://github.com/jaraco/keyrings.alt/blob/master/keyrings/alt/file.py) which do not require interaction. Or try the [cryptfile](https://github.com/frispete/keyrings.cryptfile) backend suggested in a comment above.

Otherwise, if you want to use the Secret Service backend, you can follow the instructions in the [README](https://github.com/jaraco/keyring/blob/master/README.rst#using-keyring-on-headless-linux-systems) file.

How to change the keyring backend in your application is also [described in the README](https://github.com/jaraco/keyring/blob/master/README.rst#set-the-keyring-in-runtime).

I think there is no bug in Keyring here, so closing the issue.
