### ISSUE TITLE
is keyring/__init__.py logging.getLogger call required?

### ISSUE THREAD

**Issue by coreycb** [jaraco/keyring#291]
Is the call to logging.getLogger() in `keyring/__init__.py` required?

I ask because we are hitting a bug in Ubuntu Artful where this line of code seems to expose the issue. That line is not the root cause of the problem but it seems to expose the issue. I'd like to remove that line of code as a work-around until we can get the real fix, but would like your input on whether it's needed first.

Here's the bug I'm referring to: https://bugs.launchpad.net/ubuntu/+source/python-openstackclient/+bug/1722553

Thanks,
Corey

**Comment by jaraco** [comment]
I'm afraid I don't understand what you're asking.

> Is the call to logging.getLogger() in `keyring/__init__.py` required?

It's not required any more than the call to `import keyring` is required. But if you take that call out, the tests fail because `logger` is no longer available to be used by other modules.

Looking a little closer, I can see that that name is only used in one place in core, so it makes sense to move it there. Still, I don't understand how the presence or absence of that behavior would affect the downstream issue.

But if it will help, let's do it.

**Comment by coreycb** [comment]
Thanks @jaraco
