### ISSUE TITLE
dbus warning produced on macOS

### ISSUE THREAD

**Issue by mhucka** [jaraco/keyring#334]
The following is what I see when I import keyring in Python 3 on a macOS 10.13 system:
```
# python3                                                                                                 library/repos/turf
Python 3.5.5 (default, Mar 29 2018, 16:22:58)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
dbus[2365]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
dbus[2365]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
```
My copy of the keyring package was installed using pip:
```
# pip3 list | grep -i keyring
keyring                            13.0.0
The documentation for keyring mentions the need for dbus on Linux, but does not appear to say anything about a similar requirement for macOS, yet simply importing keyring results in the message about "dbus" shown above.
```
From the symptoms, it seems as if keyring unconditionally tries to load the dbus module even on macOS. From a quick look at the code, I could not immediately see _where_ that was happening, but if someone could point me in the right direction I could see about creating a PR to make it stop.

**Comment by jaraco** [comment]
I don't see this output on my mac.

But it may be you also have some additional dbus libraries installed.

The way keyring works is it loads a number of backends as advertised by your installed libraries, and asks each to present it's viability and priority. Here's what I see when I check the priority on that backend on my system:

```
keyring master $ python
Python 3.7.0rc1 (v3.7.0rc1:dfad352267, Jun 12 2018, 01:00:10)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring.backends.kwallet
>>> keyring.backends.kwallet.DBusKeyring.priority
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaraco/Dropbox/code/main/keyring/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/Users/jaraco/Dropbox/code/main/keyring/keyring/backends/kwallet.py", line 35, in priority
    raise RuntimeError('python-dbus not installed')
RuntimeError: python-dbus not installed
```

My guess is you have dbus installed and that's somehow emitting log output as it attempts to connect to it.

Perhaps that gives some hints as to how to debug.

**Comment by mhucka** [comment]
It looks like PyQt installs a dbus module. Would it make sense to further conditionalize the loading of the keyring backends based on OS? I.e., not just test for presence of dbus, but also that it's not macOS? (That's assuming there's no way to make it work with dbus on macOS.)

**Comment by jaraco** [comment]
My guess is that DBus on macOS would have no benefit as a transport to the macOS keychain and that a kwallet keychain isn't in the cards. So I'd like to find a way to suppress the warning message. I'd rather suppress the warning rather than bypass the behavior based on secondary factors.

In other words, it should be possible to test dbus to determine its viability without triggering warnings.

I imagine it might be possible to capture the stderr, something like:

```
    with capture_stderr():
        try_connect_dbus()
```

I'd feel better with a solution like that. Even better, though, would be for the Python APIs to offer a means to suppress the warnings.

I'm not sure which system is responsible for this message. Would you be willing to track down the software that's producing this warning and get their opinion on how they recommend polling the dbus without triggering the warning?

Failing that, let's just suppress the output.

**Comment by jaraco** [comment]
Feel free to revive this conversation if this issue is still something you'd like to pursue.
