### ISSUE TITLE
keyring keeps popping up the message: Error when attempting to decrypt the wallet kdewallet using GPG

### ISSUE THREAD

**Issue by yurivict** [jaraco/keyring#336]
See the original description here: https://github.com/biolab/orange3/issues/3120#issuecomment-402877297

keyring is just one of the libraries used in Orange, and popping up the message once should be sufficient.

**Comment by jaraco** [comment]
I'm not sure what can be done here. The reported error message is not part of this library, so it may not be possible to address the issue here. Someone will need to dig deeper to locate the code that's presenting the error message and characterize the mechanism that leads to the popup and devise a plan to prevent it.

**Comment by jaraco** [comment]
Closing as languishing, but I welcome revival at any point.

**Comment by Myzel394** [comment]
I was also facing this issue for quite some time now. I completely removed `python-keyring`, which somehow also uninstalled poetry and reinstalled poetry - now everything seems to be working
