### ISSUE TITLE
Obscure error when credential is longer than allowed

### ISSUE THREAD

**Issue by arkanoid87** [jaraco/keyring#355]
Using Windows backend, when supplying a password of a sufficient length, the following error is observed: `win32cred.CredWrite(credential, 0) -> (1783, 'CredWrite', 'The stub received bad data')'.`

**Comment by arkanoid87** [comment]
Nevermind, solved.

If you encounter this, it is due to maximum password length in windows vault.

**Comment by jaraco** [comment]
I'd still like to see this addressed, to trap the error and return a better one... or since the error message is obscure and doesn't talk about limitations, maybe just hard-code the limitation and return a nicer error message when the password length exceeds the limits.

I can't tell exactly what the limits are, but [these docs get close](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/ns-wincred-_credentiala). I welcome contribution to this issue, especially from someone with some familiarity with CredentialVault.

@zooba If you know anybody who would like to help with this issue, please let them know. Thanks, sorry for the ping, and feel free to unsubscribe.

**Comment by zooba** [comment]
Happy to be pinged :)

My reading of the docs is that the limit is always 512 bytes. So trapping the error and rewriting it when this limit is exceeded sounds fine. I wouldn't preempt the check, just in case the limit gets raised one day - rewriting a known error is safer.

(The "513 bytes" limit for username is to include a trailing null, which the blob does not require because the size is passed explicitly.)

**Comment by ahqardah** [comment]
@jaraco we are facing the same issue on windows 10 and windows server 2019

```
File "{userpath}\appdata\local\continuum\miniconda3\envs\bonsai\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "{userpath}\appdata\local\continuum\miniconda3\envs\bonsai\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1783, 'CredWrite', 'The stub received bad data').
```

 Are there any fixes for this?

**Comment by jaraco** [comment]
I don't have a fix for this issue and can't even conceive of a suitable, proper fix. Contributions are welcome, but given the inherent limitations of the Windows Credential Store, I don't think you're going to find a solution that allows storing of these longer credentials. I'm open to ideas and contributions.

**Comment by jaraco** [comment]
I've added a test to the suite that demonstrates that passwords of length 1024 don't produce an error. Happy to revisit if others encounter this error with a legit use-case.

**Comment by cvubrugier** [comment]
Thanks @jaraco for developing and maintaining the Python keyring library.

I faced this issue in an application we are developing at work. No worry, we are going to workaround it by paying attention to the length of the secret we store in the Windows Credential Manager.

Out of curiosity, I determined through dichotomy that the maximum password length accepted by the Windows Credential Manager is **1280** characters:

    >>> import keyring
    >>> keyring.set_password('foo', 'bar', 'a' * 1280)
    >>> keyring.set_password('foo', 'bar', 'a' * 1281)
    Traceback (most recent call last):
      File "C:\Users\Foo\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
        yield
      File "C:\Users\Foo\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\pywin32\win32cred.py", line 37, in CredWrite
        _authentication._CredWrite(c_pcreds, 0)
      File "C:\Users\Foo\AppData\Local\Programs\Python\Python39\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 53, in check_zero
        raise make_error(function, function_name)
    OSError: [WinError 1783] The stub received bad data.

**Comment by jrobbins-LiveData** [comment]
@jaraco I know this issue is closed, but the Windows limit is getting in our way, too, and I have a possible idea for how to fix it.

Here's the version of Windows I'm on

```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎5/‎1/‎2021
OS build	19043.1320
```

The limit documented by @cvubrugier is the same limit I am experiencing: 1280 max for the password.

Yet some packages use `keyring` to store tokens (JWT) in `keyring`, and these tokens can easily exceed 1280 bytes.

So my idea is to edit `https://github.com/jaraco/keyring/blob/main/keyring/backends/Windows.py`, in particular `_set_password` and `_get_password`, notice the "too big" password, and split it up into as many pieces as necessary, giving each one a unique (and numbered) `TargetName`.  

Since `_set_password` and `_get_password` are the callers of `win32.CredWrite` and `win32.CredRead`, I can transparently split the password up in `_set_password` and then transparently re-join it up in `_get_password` and no other code will be the wiser for it.

I've prototyped this and it works.

Is this a PR you would potentially welcome (or, minimally, indulge?)
