### ISSUE TITLE
keyring 16.0.0 breaks keyrings.alt.file.PlaintextKeyring

### ISSUE THREAD

**Issue by basak** [jaraco/keyring#357]
Steps to reproduce:

Start a fresh Python 3 environment on Ubuntu Bionic. For example:

```
lxc launch ubuntu:bionic keyring
lxc exec keyring -- login -f ubuntu
sudo apt update && sudo apt -y install virtualenv
virtualenv --python=python3 keyring
. keyring/bin/activate
```
Install `keyring` 16.0.0 and `keyrings.alt`:

```
pip3 install keyring==16.0.0 keyrings.alt
```
(this uses `keyrings.alt` 3.1 which is currently the latest in PyPI)

Run the following:

```
python3 -c 'import keyring; print(keyring.get_keyring())'
```

Expected result:

```
keyrings.alt.file.PlaintextKeyring (priority: 0.5)
```

Actual result:

```
keyring.backends.fail.Keyring (priority: 0)
```

Downgrading `keyring` to 15.2.0 works around the problem:

```
$ pip3 install keyring==15.2.0
[...]
$ python3 -c 'import keyring; print(keyring.get_keyring())'
keyrings.alt.file.PlaintextKeyring (priority: 0.5)
```

**Comment by mitya57** [comment]
I would say it is an issue in keyring itself, not in keyrings.alt.

For some reason the new [`_create_chained_backend` method](https://github.com/jaraco/keyring/blob/master/keyring/core.py#L86) ignores backends with priority < 1, such as PlaintextKeyring.

If I replace the check on line 91 with `priority > 0` then it almost works. I say almost because `print(keyring.get_keyring())` still fails: ChainerBackend has no priority, so its `__str__` method fails.

@jaraco Can you look at this please?
