### ISSUE TITLE
Keyring doesn't automatically select the default secret store per OS

### ISSUE THREAD

**Issue by ahqardah** [jaraco/keyring#418]
**Describe the bug**
Keyring doesn't select the default secret store per OS, for example, on OS_X, it's supposed to select the keychain (should be with highest priority?). instead it selects some other keychain, specially, if another one in installed, example cryptfiles.

**To Reproduce**
 install multiple keyrings, example, default keyring and cryptfiles.
list available keyrings.
```
keyrings.cryptfile.file.PlaintextKeyring (priority: 0.5)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.OS_X.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyrings.cryptfile.cryptfile.CryptFileKeyring (priority: 2.5)
keyrings.cryptfile.file.EncryptedKeyring (priority: 0.6)
```
as we can see, the default keyring (OS_X.Keyring does not have the highest priority).

**Expected behavior**

**Environment**

- OS: MacOS, and Windows.

**Comment by jaraco** [comment]
It does automatically select the _best_ backend for the environment. Because you've installed `keyrings.alt`, you have two backends, `OS_X.Keyring` and `CryptFileKeyring` with a priority greater or equal to 1, so the `Chainer` backend becomes available to chain those two preferred keyrings together. In practice, that should work fine - OS_X has i higher priority so will be used for storing passwords, and since there are no passwords stored in the CryptFileKeyring, then it should never prompt for a password to encrypt. Is there some reason it's not working for you?

**Comment by ahqardah** [comment]
So, if I understand this correctly, it will automatically select the `OS_X.Keyring`? Let me repro this and submit the exact behavior I am getting.

**Comment by jaraco** [comment]
Well, from a backend perspective, the `Chainer` will be selected, but the `Chainer` will chain requests to each of the backends with priority `>=1` in order of priority. In most cases, that will behave exactly as you'd expect if only the `OS_X.Keyring` were the sole backend.
