### ISSUE TITLE
keyring is skipped due to an exception: 'WindowsPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by javedsha** [jaraco/keyring#421]
I am getting the following error when running `pip install` for any package on my windows PC:

```
keyring is skipped due to an exception: 'WindowsPath' object has no attribute 'read_text'
```

On my laptop which has windows too, keyring is working.

Version: 21.1.0

Note: I am using [artifacts-keyring](https://pypi.org/project/artifacts-keyring/) to install the packages, not sure if it matters.

**Comment by jaraco** [comment]
Searching for that error message, I found WhyNotHugo/python-barcode#52, which indicates that the error means you have an old, unsupported version of Python (prior to 3.4). Can you confirm your Python version?

> On my laptop which has windows too, keyring is working.

I'll bet your laptop has a newer Python or an older pip (prior to keyring adoption).

Since you have a working and non-working environment, I'll leave it to you to figure out what the problem is, and if it happens to be with the keyring library (on a supported Python version), please let us know.
