### ISSUE TITLE
On macOS, secrets are accessible without a password prompt to any Python script (even if you've set them in a different venv)

### ISSUE THREAD

**Issue by jfaust** [jaraco/keyring#457]
**Describe the bug**
Secrets stored in the macOS Keychain are accessible with no prompt to any Python script. I saw in #282 that using a virtualenv should fix this, but as far as I can tell it does not.

This feels like a pretty significant security hole - the effect is that any Python script can access any secret stored w/Keyring.

**To Reproduce**
1. Install `keyring` in a `venv`
```
python3 -m venv test-keyring
cd test-keyring
source bin/activate
pip3 install keyring
```
2. Set a secret: `keyring set ...`
3. In another terminal, create another `venv`, activate it and install keyring
4. In the 2nd `venv`, retrieve the same secret via `keyring get ...`
5. It retrieves the secret with no password prompt.

**Expected behavior**
The secrets should only be accessible (without a prompt) from within the `venv` they were set in.

**Environment**

- OS: macOS 10.15.5

```
$ pip list | grep keyring
keyring                  21.3.0
$ keyring --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.OS_X.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: -1)
```

**Other Context**

If I look in the `Keychain`, all the secrets set this way reference the same Python executable, presumably because the `venv` symlinks them.

I tried the same thing with `virtualenv` with the same result.

**Comment by jaraco** [comment]
Thanks for the report.

> The secrets should only be accessible (without a prompt) from within the `venv` they were set in.

I believe this expectation is contradictory to the intentional design of the library. This library mainly aims to provide access to the underlying service's secret store. In fact, it aims to provide access across virtualenvs and possibly even across other applications. For example, I use keyring to retrieve passwords that are also used by the `git` command.

The keyring library has comparable behavior with other backends. On Windows, the credentials are stored centrally in the Credential Manager. On Linux, they're stored in another centralized storage. There's (currently) no feature that discriminates by virtualenv (or no venv at all).

The isolation is handled by the backend. Usually, the isolation is based on a user's session (any logged in user can access any credential saved by that user). If the backend allows different executables to access the credentials, then so does keyring. If the backend allows the same executable to access credentials and venv re-uses that same executable, keyring does not interfere in that abstraction.

An in fact, it's a desirable feature that credentials are accessible across virtualenvs. Many users, including myself, rely on the fact that these credentials are long-persisted and available across different environments and versions of Python. For example, I'm relying on keyring to retrieve credentials that were created on older versions of Python from a decade ago (although many of these credentials may have been updated in the meantime). It would be a grand hassle if users had to keep separate copies of these credentials per Python release or virtualenv.

Can you describe more about your use-case that would benefit from per-env credentials? Perhaps there's a way that an opt-in plugin could supply this behavior.

**Comment by jfaust** [comment]
Sorry, I think I miscommunicated my issue - I agree that having access to the same secrets in the keyring is crucial. The part that was unexpected to me is that any Python application gets access to them *without a password prompt*, which goes contrary to your comment in #282
```
Even just using a virtualenv or updating Python will cause a new warning prompt for that credential
```

I was expecting that using a virtualenv would make it so that other virtualenvs (or the global Python interpreter) would prompt for a password if it tried to access a password. Instead, every virtualenv just gets immediate access without a password prompt.

Right now tools like [ofxtools](https://github.com/csingley/ofxtools) are using `keyring` to store banking credentials in the osx keychain, where they are then accessible without a password prompt to any Python script - that's the part I was surprised/concerned about.

**Comment by jfaust** [comment]
Also, I'm not sure there's actually anything that can be done about this - if OSX treats the Python executable as the owner, then the only thing to do is to install a separate python executable, and use it for that virtualenv (which is my current plan). This may be more a question of documentation/warnings in the docs than anything else.

**Comment by dany74q** [comment]
I've been researching this topic for a couple of days - I think I have some insights.

The keychain implementation in OSX carries some baggage from the iOS counterpart;
Specifically, one can't restrict access to keychain items, nor use the TPM, when running from an 
executable which isn't code-signed with an apple developer id along with some specific entitlements[1].

This poses an annoyance for interpreters like python, which you wouldn't be able to guarantee that
the user's used binary is signed.

I believe that this is the case because some of the ACL behavior, and namely, support for
touch-id and user presence prompt, were first available in iOS, or have been backported
from iOS to mac to preserve some layer of compatibility between the implementations.

This implementation detail leaks because in order to work with ACLs, TPM, access groups,
and similar mechanisms, you usually have to explicitly set the `kSecUseDataProtectionKeychain` flag[2],
which, from the docs, `Set the value for this key to true... when accessing a macOS keychain item that behaves like an iOS keychain item`.

[1] https://developer.apple.com/forums/thread/658711
[2] https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain?language=objc

**Comment by jaraco** [comment]
@jfaust, thanks for the clarification. I do think you're right that the virtualenv re-uses the same executable, so macOS won't detect it as a different executable than the original Python. Using a separate executable _might_ serve your purposes.

Were you aware that the keychain is also (mainly) protected by your login, so that someone with access to the file system or logged in with a different account would not have access to the credentials? That's where the main security lies and not with which executable has access to the credential.

> Even just using a virtualenv or updating Python will cause a new warning prompt for that credential

I think the reason for that comment was because we were using `virtualenv` (and not `venv`) and those versions of virtualenv would copy the Python executable. Later versions will symlink the executable. The behavior encountered when that comment was made is no longer present and was never part of the design.

What is the attack vector you're looking to protect? What's the harm in different python environments sharing access to the credential? What warning would you suggest to be added to the docs?

**Comment by jaraco** [comment]
Thanks @dany74q for the additional insight. I'm not sure I understand the implications of this information. It does seem that keyring's usage of the keychain fits into the "legacy" mode. Let me know if you have any recommendations on how to leverage this information.

**Comment by dany74q** [comment]
Hey @jaraco, just to synthesize this a bit further - in order to guarantee touch-id / password be prompted before 
accessing a specific secret, one must use the iOS keychain items.

We can't really utilize keychain access control in keyring by default, because they require the calling executable to be signed with specific entitlements, which won't be the case for non-custom compiled python executables.

I don't think then, that we would be able to enforce that scripts using the same interpreter would not be able to read stored keys.

**Comment by jfaust** [comment]
@jaraco Yes, I'm aware of the security around keychain for different users. The vulnerability I'm concerned with it a malicious package/app that a user has downloaded.

Interestingly, using `venv --copies`, which copies the executables instead of symlinking them, also did not do what I expected - those venvs could access credentials without a password prompt. I'm wondering if OSX uses the hash of the binary to know it's the same executable - or if there's some sidechannel data in the filesystem that is also getting copied.

Using a separate interpreter entirely (built from source) worked as expected. This isn't a perfect solution, since a malicious app could search the system and find this interpreter, but it at least obfuscates it a little.

There are two attack vectors I'm thinking about:

1. User downloads a malicious app - any app that can execute the python interpreter can access any secrets stored by `keyring`
1. Something malicious is injected in a pypi package - I'm not aware of this happening in pypi specifically, but it has certainly happened in the `npm` ecosystem. Any time that package is then used, it gets access to any secrets stored by `keyring`

I think the warning I'd suggest is something along the lines of:
```
On macOS, any Python script or application can access secrets set using keyring without prompting the user for a password. If there are specific secrets you would like to always prompt for your password when accessed, you can manually remove Python from their Access Control settings in the Keychain Access application.
```

**Comment by jaraco** [comment]
Good work on `--copies`. Thanks for capturing that variable.

I agree, you may be right about capturing a hash of the executable. I have observed that I have to re-authorize access to keychain items after upgrading Python, which similarly would change the hash.



> I think the warning I'd suggest is something along the lines of

Your wording is good. I like it. Perhaps there should be a section describing "security considerations" for any of the built-in, recommended backends, including "no analysis has been performed" (highlighting that a null declaration is not the same as "nothing to consider").

Would you be willing to draft a PR for the README to start to capture this concern in a way that honors all built-in backends?

**Comment by jfaust** [comment]
That makes total sense - I'm happy to draft something, though it may take me a few days.
