### ISSUE TITLE
How to retrieve the keyring version programmatically?

### ISSUE THREAD

**Issue by giumas** [jaraco/keyring#476]
Is it possible to retrieve the version of the library programmatically?
I was unable to find the '`__version__`' value in the code.

**Comment by mitya57** [comment]
I think it is only possible to retrieve the version from metadata:
```python
>>> from importlib.metadata import version
>>> version('keyring')
'21.5.0'
```

See https://docs.python.org/3/library/importlib.metadata.html#distribution-versions.

**Comment by jaraco** [comment]
Originally, I'd intended for projects to expose their versions through a `__version__` attribute, but it turns out to do that requires adding a lot of boilerplate and dependencies on backports... and for most users, that's not particularly helpful. So I've instead opted to leave it to those clients to resolve the version of the package when needed exactly as mitya57 has suggested.
