### ISSUE TITLE
AttributeError: module 'keyrings.alt' has no attribute 'file'

### ISSUE THREAD

**Issue by elig0n** [jaraco/keyring#490]
**Describe the bug**
Trying to run a program which accesses the keyring:

```
Traceback (most recent call last):
  File "/usr/bin/pb", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pushbullet_cli/app.py", line 94, in main
    if isinstance(keyring.get_keyring(), keyrings.alt.file.EncryptedKeyring):
AttributeError: module 'keyrings.alt' has no attribute 'file'
```

Trying to run the example code from README.md:
```
@>>> import keyring
@>>> keyring.get_keyring()
<keyring.backends.null.Keyring object at 0x7f4e13f550d0>
@>>> keyring.set_password("system", "username", "password")
@>>> keyring.get_password("system", "username")
@>>> 
```

**Environment**

- OS: arch linux
- Python 3.9.1
- keyring==21.4.0
- keyrings.alt==4.0.2

```
$ keyring --list-backends
...
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.null.Keyring (priority: -1)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyrings.alt.file.PlaintextKeyring (priority: 0.5)
keyring.backends.kwallet.DBusKeyring (priority: 4.9)
keyring.backends.SecretService.Keyring (priority: 5)
keyrings.alt.Gnome.Keyring (priority: 1)
keyrings.alt.file.EncryptedKeyring (priority: 0.6)
```
**Additional context**
I ran some functions from the module in python for example `keyring.core.disable()`
which might have caused this, I'm not sure.

**Comment by elig0n** [comment]
It looks like I have to explicitly `import keyrings.alt.file` because neither keyrings.alt nor keyrings.alt.file would be accessible if I simply import keyrings

**Comment by jaraco** [comment]
I'm suspicious that you're not running keyring 21.4.0, but actually running keyring 21.6.0 or later. That version [removed the eager initialization](https://keyring.readthedocs.io/en/latest/history.html#v21-6-0).

Unfortunately, with the information above, I can't tell what it would take to trigger the problem. Clearly `keyrings.alt.file` is getting imported (because `keyrings.alt.file.PlaintextKeyring` is present in `--list-backends`).

Oh, I may have an idea. If you've run `keyring.core.disable()`, that will explicitly set a keyring and disable the discovery mechanism... so plugins won't be loaded and those plugin modules won't be imported. That's by design.

So the assumption that `pushbullet_cli` is making is missed. Those modules won't always be imported, and it probably should find a way to ensure that they are.

**Comment by jaraco** [comment]
Please comment if you wish to follow up.
