### ISSUE TITLE
Unable to set keyring to OS_X.Keyring

### ISSUE THREAD

**Issue by felixgao** [jaraco/keyring#504]
**Describe the bug**
The keyring must be a subclass of KeyringBackend

**To Reproduce**
1. poetry install keyring
2. add the following code
```
import keyring
from keyring.backends import OS_X
keyring.set_keyring(OS_X.Keyring)
```
3. run the script

**Expected behavior**
the keyring is set to OSX's keyring

**Environment**

- OS: OS X 10.15.7

```
$ pip list | grep keyring
keyring                   23.0.0
...
$ keyring --list-backends
keyring.backends.macOS.Keyring (priority: 5)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)
...
```

**Additional context**
installed using poetry with .venv  created via pyenvs 
python version is 3.6.12

**Comment by jaraco** [comment]
The error message is incorrect. It should say "The keyring must be an instance of KeyringBackend". You need to pass an instance of the backend, i.e. `keyring.set_keyring(OS_X.Keyring())`. Also, be aware that since keyring 22 and later, you should prefer `keyring.backends.macOS` to `keyring.backends.OS_X`.

**Comment by jaraco** [comment]
By the way, if you're on macOS, you don't need to set the keyring. It will be discovered automatically (based on the priorities).
