### ISSUE TITLE
Lost keychain entries in EC2 instances

### ISSUE THREAD

**Issue by earonesty** [jaraco/keyring#509]
**Describe the bug**
During the course of testing, we noticed an EC2 instance whose keychain entries were removed on reboot.

Our server software was still installed... but the keychain was gone.

**To Reproduce**
Create an EC2 instance.   Add an entry using py keyring.   Do something in amazon maybe involving password reset?   keyring will be empty.

If the keyring contains critical/non-reproducible keys... this could be very serious.

**Solution**
We decided to write a new Windows backend using the windows DPAPI:

https://gist.github.com/earonesty/2110460bc8df47475bd1bcd073eb5388

Not sure how best to publish/make a plugin nice for others.

**Comment by jaraco** [comment]
I'd bring up the issue with Amazon or Microsoft. All Keyring does is using the Credential Vault API](https://docs.microsoft.com/en-us/windows/win32/secauthn/credentials-management). My guess is that EC2 is doing some magic that loses user-local state to be lost between restarts.

Oh, wait. You said,

> Do something in amazon maybe involving password reset

Yes, resetting the user's password will invalidate all stored credentials. That's by design.

You can verify this behavior in the [Credential Manager UI](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0) without involving keyring at all. Add a credential, reset the password externally, then see the effect in credential manager.

I don't think there's not much Keyring can do here, but if you find my description above is inaccurate or that there is something keyring could/should do differently in the situation you describe, please do suggest.



> We decided to write a new Windows backend using the windows DPAPI:
> 
> https://gist.github.com/earonesty/2110460bc8df47475bd1bcd073eb5388
> 
> Not sure how best to publish/make a plugin nice for others.

Oh, that's interesting. It looks like the DPAPI is somehow able to encrypt content using some key stored with the user account. I'm a little surprised this technique isn't affected by the same security controls that invalidate stored credentials, but I admit I don't have a lot of experience with DPAPI.

If you want to publish your library, have a look at [the docs on third-party backends](https://github.com/jaraco/keyring#third-party-backends) and look to those projects for inspiration. Let me know if you have questions.
