### ISSUE TITLE
Improvement  - Splitting the backends into extras.

### ISSUE THREAD

**Issue by syrull** [jaraco/keyring#532]
Hello, I've been using the `keyring` to support the keychain access in macos, however one of our pipelines broke becuase cryptography required the `rust-setuptools`. I think it would be a better idea if this package can be split into extras since I won't be needing the rest of the backends a very simple solution could be something like that:

```
$ pip install keyring[macos] 
..
$ pip install keyring[windows]
```

I am willing to work on this alternative if the author is interested!

**Comment by jaraco** [comment]
I've considered something similar, but instead of extras, use platform markers:

`install_requires = keyrings.macos; sys_platform=="darwin"`

There are some reasons I haven't embarked on this yet:

- I've been (thusfar) successful in making the modules portable.
- Splitting the backends would create lots of new packages that each need their own maintenance.
- Some already external backends could rely on the functionality in some of the backends.
- Specifically with extras, requiring extras will be a noisy burden. If a project like 'twine' wants to require 'keyring', they would need to supply extras for all environments they target.

Can you say more about the failure mode?

> one of our pipelines broke becuase cryptography required the `rust-setuptools`

keyring doesn't require cryptography and the windows and linux-specific dependencies are already keyed on platform.

**Comment by syrull** [comment]
I think you are right about that, we ended up using the platform markers instead. 

One of the sub dependencies `SecretStorage` is requiring the cryptography package: https://github.com/mitya57/secretstorage/blob/master/setup.cfg 

I also dug around our RHEL Server (where the error was happening) and there was some tricky stuff around `dnf` not updating/installing some deps. The whole thing is documented in the cryptography package (https://cryptography.io/en/3.4.5/installation.html#rust) 

Anyways that concludes it all, thanks for the reply I am closing the ticket.
