### ISSUE TITLE
Add pass to keyring

### ISSUE THREAD

**Issue by fabien-joubert** [jaraco/keyring#565]
I use [pass](https://www.passwordstore.org/) to manage my credentials on GNU Linux. As far as I know it is widely spread on Linux distributions, even the headless ones.  

It would be great if Keyring support it.  
Let me know what you think.

**Comment by matthewsht** [comment]
https://github.com/nazarewk/keyring_pass

Works and I use it here. Its a simple/good wrapper around the pass command line program, thus its kinda slow.
A full python implementation would be faster but I've not seen one yet.

**Comment by fabien-joubert** [comment]
Thank you for your reply.  
What do you mean by "full python implementation"? And could you explain why it would be faster?

**Comment by matthewsht** [comment]
pass is implemented in shell, calling tree, grep, and a few others, plus GPG itself for the encryption/decryption.

I *think* a python implementation that did all (or whatever is needed for keyring) of what pass does in native python would be faster, even if still calling out to GPG for the enc/decrypt step. The cost is the fork/exec of those other tools, plus the fact that keyring is asking for something fairly specific and likely _some_ shortcuts can be taken.
Forking/execing GPG is still a cost, but I'm not aware of python code that could do the equivalent crypto natively.

I look forward to being corrected by those better informed - I'd love a more performant keying pass backend. :)

**Comment by jaraco** [comment]
I'm so glad to hear the plugin framework is doing its job. Please let me know if there's any more that keyring should be considering here.

**Comment by mcepl** [comment]
Does anybody have an experience with http://github.com/notandy/pass_python_keyring , which seems to be the alternative implementation of the same?

**Comment by matthewsht** [comment]
None, but I'll try and test this - any experience yourself?

--
Hunter Matthews
Scientific System Engineer [C]
NIH/National Human Genome Research Institute
***@***.******@***.***> | (919) 491-2124







On Sep 20, 2022, at 5:38 AM, Matěj Cepl ***@***.******@***.***>> wrote:



Does anybody have an experience with http://github.com/notandy/pass_python_keyring<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotandy%2Fpass_python_keyring&data=05%7C01%7Chunter.matthews%40nih.gov%7Cc444bcb9c8a04b99adbf08da9aebdda3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637992635068257542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eLy%2BEWOftojkB%2B6f8oTTA%2BgC%2BRWPH34tZHiHFK6dwfM%3D&reserved=0> , which seems to be the alternative implementation of the same?

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjaraco%2Fkeyring%2Fissues%2F565%23issuecomment-1252098102&data=05%7C01%7Chunter.matthews%40nih.gov%7Cc444bcb9c8a04b99adbf08da9aebdda3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637992635068257542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bYvg2HHqmPFYx4P1pwqRwipFAXFjSlQjsJpZjr1JZ0Y%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATFEQQ3UP4OWIK7ZWCKUVATV7GAZBANCNFSM5PIEJZJA&data=05%7C01%7Chunter.matthews%40nih.gov%7Cc444bcb9c8a04b99adbf08da9aebdda3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637992635068257542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2gxf2HvRKn6JS4qUYTZVfLBrz6ZOYVecp406O%2BCPNyw%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by mcepl** [comment]
> None, but I'll try and test this - any experience yourself?

Don’t bother, https://github.com/notandy/pass_python_keyring is quite broken.
