### ISSUE TITLE
two keyring password dialogs are triggered

### ISSUE THREAD

**Issue by bwagner** [jaraco/keyring#644]
**Describe the bug**

If name1 is a **substring** of name2, **two** dialogs are triggered to retrieve either of their passwords.
The first dialog reads:
`python3.11 wants to use your confidential information stored in "myorg" in your keychain.`
![image](https://github.com/jaraco/keyring/assets/447049/808485fe-37b1-4503-9471-d11e10fb8a02)
After entering the keyring password, the second dialog appears:
`python3.11 wants to access key "myorg" in your keychain.`
![image](https://github.com/jaraco/keyring/assets/447049/78a7cb3d-fb14-4def-b443-f96e0b47cc6f)

**To Reproduce**
1. Start Keychain Access application.
2. Create two passwords, where the name of one is a substring of the other name, e.g. `"myorg"`and `"myorg-api"`.
<img width="874" alt="image" src="https://github.com/jaraco/keyring/assets/447049/8fa4f69e-8b3c-4517-b117-2b73543b521a">

4. retrieve one of the passwords, e.g. `python -c 'import keyring;print(keyring.get_password("myorg", "user1"))'`
5. See two dialogs

**Expected behavior**
The keyring password should only be requested once.

**Environment**

- OS: macOS 13.4.1 (Ventura)
- Python: 3.11.4

```
keyring 24.2.0
...
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.macOS.Keyring (priority: 5)
...
```
Strangely, when creating those entries in keyring using **python** and after deleting "python3.11" from "Access Control" within the [Keychain Access](https://github.com/jaraco/keyring#security-considerations) app, the keychain password is requested only once, as expected!

**Comment by jaraco** [comment]
I suspect the issue is unrelated to the presence of a substring. I use the macOS keyring and it frequently prompts me twice for the keychain password with two different prompts.

To test this assumption, I added just one password to my keychain:

![image](https://github.com/jaraco/keyring/assets/308610/af04eb74-7b59-4162-aca0-169792f386d8)

I then ran the command as indicated and was prompted for the password twice. I have a habit of selecting Always Allow because if I select simply Allow, it frequently prompts twice, as it did here. If I chose Always Allow, I'm prompted only once. Regardless, it appears the substring is a red herring. The issue is that macOS prompts twice for a single credential retrieval. Even after retrieving the password, I'm repeatedly prompted twice for the keyring password to retrieve the credential.

**Comment by jaraco** [comment]
Tracing the code for the macOS backend, the "get" operation only calls the API once ([here](https://github.com/jaraco/keyring/blob/c65f00dc5c5ccfc2c98ca7061054a7ae918ba437/keyring/backends/macOS/api.py#L140)). There's nothing that Keyring is doing that's triggering the multiple password prompts. It's Apple's own logic that's forcing the password prompt twice. I don't know why it does it.

Most users have the keyring configured with the same password as the user's login, so the keychain is unlocked by default and password prompts are bypassed. I'm unsure why that's not the case for your application. The only reason I notice it is because I keep a separate keychain, "home".

I don't think there's anything keyring can do to overcome Apple's limitations here.

I welcome ideas or suggestions or further lines of inquiry.

**Comment by jaraco** [comment]
See also #619, which is slightly related.
