### ISSUE TITLE
Unable to install dbus-python on Ubuntu 23.10

### ISSUE THREAD

**Issue by iirekm** [jaraco/keyring#679]
Installing `dbus-python` is a nightmare. I'm unable to do it on my Ubuntu 23.10.

Couldn't keyring library use something else, e.g. an alternative, better-maintained library for dbus (there are a few), or command line tool called `kwalletcli`?

**Comment by mitya57** [comment]
The primary backend for keyring is SecretStorage, which uses [jeepney](https://gitlab.com/takluyver/jeepney) — a pure Python D-Bus library, installing which is _not_ a nightmare.

And KWallet supports the Secret Service protocol since [version 5.97](https://invent.kde.org/frameworks/kwallet/-/merge_requests/11). Ubuntu 23.10 ships with version 5.110.
